openapi: 3.0.0
info:
  title: Miro-like Without Api
  description: API from Miro
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register"
  
  /auth/refresh:
    post:
      $ref: "./endpoints/auth.yaml#/refresh"

  /boards:
    get:
      $ref: "./endpoints/boards.yaml#/getAllBoards"
    
    post:
      $ref: "./endpoints/boards.yaml#/createBoard"
  
  /boards/{boardId}:
    delete:
      $ref: "./endpoints/boards.yaml#/deleteBoard"